### ISSUE TITLE
Unable to parse measure template after upgrade

### ISSUE THREAD

**Issue by chubert-sb** [cqframework/sample-content-ig#101]
After upgrading from 0.4.1 to 0.4.2, there seems to be an issue parsing the Measure template. We've been using the LiquidEngine to parse the measure. After upgrading, we get the error below:

`org.hl7.fhir.exceptions.FHIRException: Script hr-script: Script hr-script: Unknown flow control statement assign counter = 1
	at org.hl7.fhir.r5.utils.LiquidEngine$LiquidParser.parseList(LiquidEngine.java:522) ~[org.hl7.fhir.r5-6.0.1.jar:na]
	at org.hl7.fhir.r5.utils.LiquidEngine$LiquidParser.parseIf(LiquidEngine.java:561) ~[org.hl7.fhir.r5-6.0.1.jar:na]
	at org.hl7.fhir.r5.utils.LiquidEngine$LiquidParser.parseList(LiquidEngine.java:507) ~[org.hl7.fhir.r5-6.0.1.jar:na]`

**Comment by chubert-sb** [comment]
To help it looks like it might have something to do with the line added in the Measure.liquid at line 372

**Comment by brynrhodes** [comment]
Closing since there have been multiple releases since this issue was reported. Feel free to reopen if this is still occurring.
